export const pagesRoutes = [
  ["v-8daa1a0e","/",{"title":""},["/index.html","/README.md"]],
  ["v-7445c193","/dbs/",{"title":"MySQL"},["/dbs/index.html","/dbs/README.md"]],
  ["v-0386ece0","/devops/docker.html",{"title":"Docker"},["/devops/docker","/devops/docker.md"]],
  ["v-71fde78e","/devops/",{"title":"DevOps"},["/devops/index.html","/devops/README.md"]],
  ["v-1b024944","/devops/webservers.html",{"title":"Apache"},["/devops/webservers","/devops/webservers.md"]],
  ["v-035484f7","/frontend/jquery.html",{"title":"jQuery"},["/frontend/jquery","/frontend/jquery.md"]],
  ["v-06198984","/frontend/",{"title":"HTML + Bootstrap"},["/frontend/index.html","/frontend/README.md"]],
  ["v-bac85f58","/php/codeception.html",{"title":"Codeception"},["/php/codeception","/php/codeception.md"]],
  ["v-32167696","/php/debug.html",{"title":"Docker based"},["/php/debug","/php/debug.md"]],
  ["v-6816e42c","/php/phalcon.html",{"title":"Phalcon"},["/php/phalcon","/php/phalcon.md"]],
  ["v-744b4c30","/php/",{"title":"General PHP"},["/php/index.html","/php/README.md"]],
  ["v-4d367973","/php/snippets.html",{"title":"PHP Utils"},["/php/snippets","/php/snippets.md"]],
  ["v-fb3f1d52","/php/test.html",{"title":"Selenium"},["/php/test","/php/test.md"]],
  ["v-f4c5b360","/php/yii2.html",{"title":"Yii2 snippets"},["/php/yii2","/php/yii2.md"]],
  ["v-63cd5dba","/python/",{"title":"Python"},["/python/index.html","/python/README.md"]],
  ["v-db500bd0","/testing/",{"title":"Various QA-related topics"},["/testing/index.html","/testing/README.md"]],
  ["v-de53e5ba","/testing/selenium.html",{"title":"Selenium"},["/testing/selenium","/testing/selenium.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
]
