<template><div><h1 id="devops" tabindex="-1"><a class="header-anchor" href="#devops" aria-hidden="true">#</a> DevOps</h1>
<h2 id="jenkins" tabindex="-1"><a class="header-anchor" href="#jenkins" aria-hidden="true">#</a> Jenkins</h2>
<h3 id="remote-jenkins-starter" tabindex="-1"><a class="header-anchor" href="#remote-jenkins-starter" aria-hidden="true">#</a> Remote Jenkins starter</h3>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token punctuation">[</span><span class="token number">2017</span>-08-25 <span class="token number">11</span>:25.25<span class="token punctuation">]</span>  <span class="token comment"># Obtain the crumb with API key ~</span>
<span class="token builtin class-name">export</span> <span class="token assign-left variable">JENKINS_URL</span><span class="token operator">=</span>http://hisat-staging.dev.global-intra.net:8080/
<span class="token builtin class-name">export</span> <span class="token assign-left variable">JENKINS_BTOKEN</span><span class="token operator">=</span>THIS_I_S_DB_TO_STG <span class="token comment"># defined for the build in config time</span>
<span class="token builtin class-name">export</span> <span class="token assign-left variable">API_TOKEN</span><span class="token operator">=</span>711b884f2c591ad3496b65bbdc55c9fa <span class="token comment"># from the user's personal page</span>
<span class="token builtin class-name">export</span> <span class="token assign-left variable">API_USER</span><span class="token operator">=</span>admin
<span class="token builtin class-name">export</span> <span class="token assign-left variable">API_CRUMB</span><span class="token operator">=</span><span class="token variable"><span class="token variable">$(</span><span class="token function">curl</span> <span class="token parameter variable">-s</span> <span class="token parameter variable">-u</span> $<span class="token punctuation">{</span>API_USER<span class="token punctuation">}</span>:$<span class="token punctuation">{</span>API_TOKEN<span class="token punctuation">}</span> $<span class="token punctuation">{</span>JENKINS_URL<span class="token punctuation">}</span>/crumbIssuer/api/json<span class="token operator">|</span> <span class="token function">cut</span> -d: <span class="token parameter variable">-f3</span> <span class="token operator">|</span> <span class="token function">cut</span> -d, -f1<span class="token operator">|</span> <span class="token function">sed</span> s@<span class="token punctuation">\</span>"@@g<span class="token variable">)</span></span>
<span class="token punctuation">[</span><span class="token number">2017</span>-08-25 <span class="token number">11</span>:28.41<span class="token punctuation">]</span>  <span class="token comment"># Start the build with API key and the obtained crumb ~</span>
<span class="token function">curl</span> <span class="token parameter variable">-s</span> <span class="token parameter variable">-u</span> <span class="token variable">${API_USER}</span><span class="token builtin class-name">:</span><span class="token variable">${API_TOKEN}</span> <span class="token parameter variable">-H</span> <span class="token string">"Jenkins-Crumb:<span class="token variable">${API_CRUMB}</span>"</span> <span class="token variable">${JENKINS_URL}</span>//me/my-views/view/MonitoringAndBackup/job/Backup/job/Import_saved_DB_to_staging/build?token<span class="token operator">=</span><span class="token variable">${JENKINS_BTOKEN}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="vbox" tabindex="-1"><a class="header-anchor" href="#vbox" aria-hidden="true">#</a> VBox</h2>
<h3 id="create-disk" tabindex="-1"><a class="header-anchor" href="#create-disk" aria-hidden="true">#</a> create disk</h3>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>VBoxManage.exe createmedium disk <span class="token parameter variable">--filename</span> <span class="token operator">&lt;</span>FILENAME<span class="token operator">></span> <span class="token parameter variable">--size</span> <span class="token operator">&lt;</span>SIZE_IN_MEGABYTES<span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="add-disk" tabindex="-1"><a class="header-anchor" href="#add-disk" aria-hidden="true">#</a> add disk</h3>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>./vboxmanage.exe storageattach "<span class="token operator">&lt;</span>VMNAME<span class="token operator">></span> <span class="token parameter variable">--storagectl</span> SATA <span class="token parameter variable">--port</span> <span class="token number">1</span> <span class="token parameter variable">--type</span> hdd <span class="token parameter variable">--medium</span> /VirtualDisks/DiskName.vhd
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="windows" tabindex="-1"><a class="header-anchor" href="#windows" aria-hidden="true">#</a> Windows</h2>
<h3 id="remote-restart" tabindex="-1"><a class="header-anchor" href="#remote-restart" aria-hidden="true">#</a> Remote restart</h3>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">shutdown</span> /m <span class="token punctuation">\</span><span class="token punctuation">\</span>REMOTE_IP /r
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div></div></template>


