<template><div><h1 id="mysql" tabindex="-1"><a class="header-anchor" href="#mysql" aria-hidden="true">#</a> MySQL</h1>
<h2 id="dbdump" tabindex="-1"><a class="header-anchor" href="#dbdump" aria-hidden="true">#</a> dbdump</h2>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>mysqldump --add-drop-database --add-drop-table <span class="token parameter variable">-v</span> --single-transaction <span class="token parameter variable">-R</span> <span class="token parameter variable">-E</span> <span class="token parameter variable">-F</span> --flush-privileges --add-locks <span class="token parameter variable">-B</span> <span class="token variable">${DBNAME}</span> <span class="token parameter variable">-p</span> <span class="token operator">|</span> <span class="token function">gzip</span> <span class="token parameter variable">-c</span> <span class="token operator">></span> dbdump_<span class="token variable">${DBNAME}</span>.sql.gz
mysqldump.exe --defaults-file<span class="token operator">=</span><span class="token string">"c:\users<span class="token entity" title="\f">\f</span>z000005<span class="token entity" title="\a">\a</span>ppdata\local<span class="token entity" title="\t">\t</span>emp<span class="token entity" title="\t">\t</span>mpdcjgcf.cnf"</span>  --set-gtid-purged<span class="token operator">=</span>OFF <span class="token parameter variable">--host</span><span class="token operator">=</span>hisatv2.global-intra.net --order-by-primary<span class="token operator">=</span>TRUE <span class="token parameter variable">--protocol</span><span class="token operator">=</span>tcp <span class="token parameter variable">--user</span><span class="token operator">=</span>root --flush-logs<span class="token operator">=</span>TRUE <span class="token parameter variable">--port</span><span class="token operator">=</span><span class="token number">3306</span> --default-character-set<span class="token operator">=</span>utf8 <span class="token parameter variable">--routines</span> <span class="token parameter variable">--events</span> --single-transaction<span class="token operator">=</span>TRUE <span class="token parameter variable">--databases</span> <span class="token string">"databasename"</span> <span class="token string">"databasename2"</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="binary-log-purge" tabindex="-1"><a class="header-anchor" href="#binary-log-purge" aria-hidden="true">#</a> binary log purge</h2>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">purge</span> <span class="token keyword">binary</span> logs before <span class="token string">'2017-05-31'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="mysql-table-recover" tabindex="-1"><a class="header-anchor" href="#mysql-table-recover" aria-hidden="true">#</a> MySQL table recover</h2>
<p>To repair a corrupted MySQL ISAM database:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>myisamchk <span class="token parameter variable">--check</span> *.MYI <span class="token punctuation">;</span> myisamchk <span class="token parameter variable">--recover</span> xxx.MYI
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="queries" tabindex="-1"><a class="header-anchor" href="#queries" aria-hidden="true">#</a> Queries</h2>
<h3 id="update-by-join" tabindex="-1"><a class="header-anchor" href="#update-by-join" aria-hidden="true">#</a> Update by Join</h3>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">UPDATE</span> shipping_price sp
    <span class="token keyword">LEFT</span> <span class="token keyword">JOIN</span> company_site cs <span class="token keyword">ON</span> sp<span class="token punctuation">.</span>company_id <span class="token operator">=</span> cs<span class="token punctuation">.</span>company_id
        <span class="token keyword">SET</span> sp<span class="token punctuation">.</span>company_site_id <span class="token operator">=</span> <span class="token keyword">COALESCE</span> <span class="token punctuation">(</span>cs<span class="token punctuation">.</span>id<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span>
    <span class="token keyword">WHERE</span> sp<span class="token punctuation">.</span>id<span class="token operator">></span><span class="token number">0</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


